# Generated by Django 5.2.1 on 2025-05-19 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('level_order', models.PositiveIntegerField(default=1, help_text='Order of the level for hierarchy')),
            ],
            options={
                'db_table': 'USER_LEVEL',
                'ordering': ['level_order'],
            },
        ),
        migrations.AddField(
            model_name='xx_user',
            name='user_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='user_management.userlevel'),
        ),
    ]
