# Generated by Django 5.2.1 on 2025-05-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_userlevel_xx_user_user_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLevel',
            new_name='xx_UserLevel',
        ),
        migrations.AlterModelTable(
            name='xx_userlevel',
            table='XX_USER_LEVEL',
        ),
    ]
