# Generated by Django 5.1.7 on 2025-05-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_xx_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='xx_notification',
            name='is_shown',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='xx_notification',
            name='is_system_read',
            field=models.BooleanField(default=False),
        ),
    ]
