# Generated by Django 5.2.1 on 2025-07-29 23:20

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_xx_notification_is_shown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xx_notification',
            name='message',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='xx_user',
            name='can_transfer_budget',
            field=encrypted_model_fields.fields.EncryptedBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='xx_user',
            name='is_active',
            field=encrypted_model_fields.fields.EncryptedBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='xx_user',
            name='is_staff',
            field=encrypted_model_fields.fields.EncryptedBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='xx_user',
            name='role',
            field=encrypted_model_fields.fields.EncryptedCharField(choices=[('admin', 'Admin'), ('user', 'User')]),
        ),
        migrations.AlterField(
            model_name='xx_userlevel',
            name='description',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
