# Generated by Django 5.2 on 2025-05-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjd_transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xx_adjdtransactiontransfer',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
