# Generated by Django 5.2.1 on 2025-07-29 23:20

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjd_transaction', '0002_xx_adjdtransactiontransfer_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xx_adjdtransactiontransfer',
            name='account_name',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_adjdtransactiontransfer',
            name='actual',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_adjdtransactiontransfer',
            name='approved_budget',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_adjdtransactiontransfer',
            name='available_budget',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_adjdtransactiontransfer',
            name='cost_center_name',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_adjdtransactiontransfer',
            name='encumbrance',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_adjdtransactiontransfer',
            name='from_center',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_adjdtransactiontransfer',
            name='reason',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_adjdtransactiontransfer',
            name='to_center',
            field=models.TextField(blank=True, null=True),
        ),
    ]
