# Generated by Django 5.1.7 on 2025-04-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='xx_BudgetTransfer',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('status', models.CharField(max_length=10)),
                ('requested_by', models.CharField(max_length=10)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('description_x', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('gl_posting_status', models.CharField(blank=True, max_length=10, null=True)),
                ('approvel_1', models.CharField(blank=True, max_length=10, null=True)),
                ('approvel_2', models.CharField(blank=True, max_length=10, null=True)),
                ('approvel_3', models.CharField(blank=True, max_length=10, null=True)),
                ('approvel_4', models.CharField(blank=True, max_length=10, null=True)),
                ('approvel_1_date', models.DateTimeField(blank=True, null=True)),
                ('approvel_2_date', models.DateTimeField(blank=True, null=True)),
                ('approvel_3_date', models.DateTimeField(blank=True, null=True)),
                ('approvel_4_date', models.DateTimeField(blank=True, null=True)),
                ('status_level', models.IntegerField(default=0)),
                ('attachment', models.CharField(blank=True, max_length=10, null=True)),
                ('fy', models.CharField(blank=True, max_length=10, null=True)),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('interface_id', models.IntegerField(blank=True, null=True)),
                ('reject_group_id', models.IntegerField(blank=True, null=True)),
                ('reject_interface_id', models.IntegerField(blank=True, null=True)),
                ('approve_group_id', models.IntegerField(blank=True, null=True)),
                ('approve_interface_id', models.IntegerField(blank=True, null=True)),
                ('report', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'XX_BUDGET_TRANSFER',
            },
        ),
    ]
