# Generated by Django 5.1.7 on 2025-05-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xx_budgettransfer',
            name='attachment',
            field=models.CharField(blank=True, default='No', max_length=10, null=True),
        ),
    ]
