# Generated by Django 5.2.1 on 2025-05-19 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_management', '0002_alter_xx_budgettransfer_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='xx_BudgetTransferAttachment',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.IntegerField()),
                ('file_data', models.BinaryField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('budget_transfer', models.ForeignKey(db_column='transaction_id', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='budget_management.xx_budgettransfer')),
            ],
            options={
                'db_table': 'XX_BUDGET_TRANSFER_ATTACHMENT',
            },
        ),
    ]
