# Generated by Django 5.2.1 on 2025-05-20 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_management', '0003_xx_budgettransferattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xx_budgettransfer',
            name='status_level',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='xx_BudgetTransferRejectReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_text', models.TextField(blank=True, null=True)),
                ('reject_date', models.DateTimeField(auto_now_add=True)),
                ('reject_by', models.CharField(blank=True, max_length=25)),
                ('Transcation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reject_reasons', to='budget_management.xx_budgettransfer')),
            ],
            options={
                'db_table': 'XX_BUDGET_TRANSFER_REJECT_REASON',
            },
        ),
    ]
