# Generated by Django 5.2 on 2025-07-29 07:56

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget_management", "0004_alter_xx_budgettransfer_status_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="xx_budgettransfer",
            name="approvel_1",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="xx_budgettransfer",
            name="approvel_2",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="xx_budgettransfer",
            name="approvel_3",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="xx_budgettransfer",
            name="approvel_4",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="xx_budgettransfer",
            name="attachment",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, default="No", null=True
            ),
        ),
        migrations.AlterField(
            model_name="xx_budgettransfer",
            name="code",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="xx_budgettransfer",
            name="description_x",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="xx_budgettransfer",
            name="fy",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="xx_budgettransfer",
            name="gl_posting_status",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="xx_budgettransfer",
            name="notes",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="xx_budgettransfer",
            name="report",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="xx_budgettransfer",
            name="requested_by",
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name="xx_budgettransfer",
            name="status",
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name="xx_budgettransfer",
            name="transaction_date",
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name="xx_budgettransfer",
            name="type",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="xx_budgettransferattachment",
            name="file_name",
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name="xx_budgettransferattachment",
            name="file_type",
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name="xx_budgettransferrejectreason",
            name="reason_text",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="xx_budgettransferrejectreason",
            name="reject_by",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
    ]
