# Generated by Django 5.2 on 2025-07-29 08:04

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget_management", "0005_alter_xx_budgettransfer_approvel_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="xx_budgettransfer",
            name="description_x",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="xx_budgettransfer",
            name="notes",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="xx_budgettransferrejectreason",
            name="reason_text",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
    ]
