# Generated by Django 5.2 on 2025-07-29 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget_management", "0006_alter_xx_budgettransfer_description_x_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="xx_budgettransfer",
            name="description_x",
        ),
    ]
