# Generated by Django 5.2 on 2025-07-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget_management", "0007_remove_xx_budgettransfer_description_x"),
    ]

    operations = [
        migrations.AddField(
            model_name="xx_budgettransfer",
            name="description_x",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
