# Generated by Django 5.2.1 on 2025-07-29 23:20

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_management', '0008_xx_budgettransfer_description_x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xx_budgettransfer',
            name='description_x',
        ),
        migrations.AlterField(
            model_name='xx_budgettransfer',
            name='amount',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='xx_budgettransfer',
            name='approvel_1_date',
            field=encrypted_model_fields.fields.EncryptedDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_budgettransfer',
            name='approvel_2_date',
            field=encrypted_model_fields.fields.EncryptedDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_budgettransfer',
            name='approvel_3_date',
            field=encrypted_model_fields.fields.EncryptedDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_budgettransfer',
            name='approvel_4_date',
            field=encrypted_model_fields.fields.EncryptedDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_budgettransfer',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='xx_budgettransfer',
            name='fy',
            field=encrypted_model_fields.fields.EncryptedIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_budgettransfer',
            name='request_date',
            field=encrypted_model_fields.fields.EncryptedDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='xx_budgettransferrejectreason',
            name='reject_date',
            field=encrypted_model_fields.fields.EncryptedDateTimeField(auto_now_add=True),
        ),
    ]
