# Generated by Django 5.1.7 on 2025-05-07 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XX_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=255, unique=True)),
                ('parent', models.CharField(blank=True, max_length=50, null=True)),
                ('alias_default', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XX_Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=50)),
                ('parent', models.CharField(blank=True, max_length=50, null=True)),
                ('alias_default', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XX_PivotFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('actual', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fund', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('encumbrance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_and_entitys.xx_account')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_and_entitys.xx_entity')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entity', 'account', 'year'), name='unique_entity_account_year')],
            },
        ),
    ]
