# Generated by Django 5.1.7 on 2025-05-07 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='xx_account',
            table='XX_Account',
        ),
        migrations.AlterModelTable(
            name='xx_entity',
            table='XX_Entity',
        ),
        migrations.AlterModelTable(
            name='xx_pivotfund',
            table='XX_PivotFund',
        ),
    ]
