# Generated by Django 5.1.7 on 2025-05-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0002_alter_xx_account_table_alter_xx_entity_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xx_pivotfund',
            name='account',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='xx_pivotfund',
            name='entity',
            field=models.CharField(max_length=50),
        ),
    ]
