# Generated by Django 5.2 on 2025-05-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0003_alter_xx_pivotfund_account_alter_xx_pivotfund_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='XX_TransactionAudit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('transfer_id', models.IntegerField(blank=True, null=True)),
                ('transcation_code', models.CharField(blank=True, max_length=50, null=True)),
                ('cost_center_code', models.CharField(blank=True, max_length=50, null=True)),
                ('account_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'XX_ADJD_TRANSACTION_AUDIT',
            },
        ),
    ]
