# Generated by Django 5.2 on 2025-05-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0004_xx_transactionaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='XX_ADJD_ACCOUNT_ENTITY_LIMIT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=255)),
                ('entity_id', models.CharField(max_length=255)),
                ('is_transer_allowed_for_source', models.CharField(blank=True, max_length=255, null=True)),
                ('is_transer_allowed_for_target', models.CharField(blank=True, max_length=255, null=True)),
                ('is_transer_allowed', models.CharField(blank=True, max_length=255, null=True)),
                ('source_count', models.IntegerField(blank=True, null=True)),
                ('target_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'XX_ADJD_ACCOUNT_ENTITY_LIMIT',
                'unique_together': {('account_id', 'entity_id')},
            },
        ),
    ]
