# Generated by Django 5.2 on 2025-05-21 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0005_xx_adjd_account_entity_limit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='XX_ADJD_ACCOUNT_ENTITY_LIMIT',
            new_name='XX_ACCOUNT_ENTITY_LIMIT',
        ),
        migrations.AlterModelTable(
            name='xx_account_entity_limit',
            table='XX_ACCOUNT_ENTITY_LIMIT',
        ),
    ]
