# Generated by Django 5.2.5 on 2025-08-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0006_alter_xx_account_entity_limit_is_transer_allowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xx_account',
            name='account',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='xx_entity',
            name='entity',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='xx_pivotfund',
            name='account',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='xx_pivotfund',
            name='actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='xx_pivotfund',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='xx_pivotfund',
            name='encumbrance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='xx_pivotfund',
            name='entity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='xx_pivotfund',
            name='fund',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
    ]
