# Generated by Django 5.2.1 on 2025-07-29 23:20

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0006_rename_xx_adjd_account_entity_limit_xx_account_entity_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xx_account',
            name='alias_default',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_account',
            name='parent',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_account_entity_limit',
            name='is_transer_allowed',
            field=encrypted_model_fields.fields.EncryptedBooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_account_entity_limit',
            name='is_transer_allowed_for_source',
            field=encrypted_model_fields.fields.EncryptedBooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_account_entity_limit',
            name='is_transer_allowed_for_target',
            field=encrypted_model_fields.fields.EncryptedBooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_account_entity_limit',
            name='source_count',
            field=encrypted_model_fields.fields.EncryptedIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_account_entity_limit',
            name='target_count',
            field=encrypted_model_fields.fields.EncryptedIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_entity',
            name='alias_default',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_entity',
            name='parent',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_pivotfund',
            name='actual',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_pivotfund',
            name='budget',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_pivotfund',
            name='encumbrance',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xx_pivotfund',
            name='fund',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
