# Generated by Django 5.2.5 on 2025-08-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0007_alter_xx_account_account_alter_xx_entity_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xx_account_entity_limit',
            name='account_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='xx_account_entity_limit',
            name='entity_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
