# Generated by Django 5.2.5 on 2025-08-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0008_alter_xx_account_entity_limit_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xx_account_entity_limit',
            name='account_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='xx_account_entity_limit',
            name='entity_id',
            field=models.CharField(max_length=50),
        ),
    ]
