# Generated by Django 5.2.5 on 2025-08-21 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial_safe'),
    ]

    operations = [
    ]
