# Generated by Django 5.2.5 on 2025-08-22 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_initial_safe'),
        ('budget_management', '0008_alter_xx_budgettransfer_transaction_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='approvalaction',
            index=models.Index(fields=['stage_instance', 'action'], name='appr_action_stage_action_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalassignment',
            index=models.Index(fields=['user'], name='appr_assign_user_idx'),
        ),
        migrations.AddIndex(
            model_name='approvaldelegation',
            index=models.Index(fields=['active'], name='appr_deleg_active_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflowinstance',
            index=models.Index(fields=['status', 'current_stage_template'], name='appr_wf_inst_status_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflowstageinstance',
            index=models.Index(fields=['workflow_instance', 'status'], name='appr_wf_stage_inst_status_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflowtemplate',
            index=models.Index(fields=['transfer_type', 'is_active'], name='appr_wf_tmpl_type_active_idx'),
        ),
    ]
